language: node_js

node_js:
  - 14

services: mongodb

install:
  - npm install

before_script:
  - sleep 15

cache: npm

before_install:
  - echo 'Installing Deps!'
  - npm i -g

script:
  - echo 'Build starts!!'
  - npm i
  - echo 'Testing!'
  - npm run test
